site_name: 放送部マニュアル
copyright: "Copyright &copy; 2022 Taisei Uemura All rights reserved."
author: WSOFT

docs_dir: "docs"
site_url: "https://housou.pages.dev/"

repo_name: "GitHub"
repo_url: "https://github.com/taiseiue/housou-manual/"
edit_uri: "blob/main/docs/"
edit_uri_template: "blob/main/docs/{path}"

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

disable_darkmode: true

theme:
  name: lantana
  locale: ja

plugins:
  - search:
      lang: "ja"
      min_search_length: 2
  - git-revision-date
  - awesome-pages
  - git-authors:
      show_email_address: true
      count_empty_lines: true
      fallback_to_empty: false
      enabled: true

markdown_extensions:
  - lantana
  - lantana.alerts2
  - lantana.selector
  - attr_list
  - lantana.cards
  - lantana.mtables
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.magiclink
  - pymdownx.striphtml
  - lantana.link_opennewtab
  - lantana.alerts
  - lantana.accordion
  - lantana.codeblock_copybtn
  - lantana.mermaid_precompile
